project_id = "jiemgpawjuranlfvmpad"

[functions.generate-checklist]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.analyze-video]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.flutterwave-webhook]
verify_jwt = false

[functions.validate-verification]
verify_jwt = false

[functions.suggest-bounty-price]
verify_jwt = true

[functions.generate-certificate]
verify_jwt = true
